spring.application.name=hessati
spring.datasource.url=jdbc:postgresql://localhost:5432/stronix-db
spring.datasource.username=postgres
spring.datasource.password=123
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver


# Max size for a single uploaded file
spring.servlet.multipart.max-file-size=10MB

# Max size for the entire multipart request
spring.servlet.multipart.max-request-size=20MB

spring.datasource.hikari.auto-commit=false

# email config
spring.mail.host=mail.stronix-rx.com
spring.mail.port=465
spring.mail.username=stronix@stronix-rx.com
spring.mail.password=Stro-2025
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true

